version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker-build.sh
      - run: ./docker-test.sh
      - run: sudo chown -R circleci:circleci logs && ./.circleci/upload-node-metrics.sh
      - run: docker tag orbs:export $DOCKER_IMAGE:$(./docker-tag.sh)
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker push $DOCKER_IMAGE
      - store_artifacts:
          path: logs

  acceptance:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker-build.acceptance.sh
      - run:
          # remove logs if the test was successful for quicker feedback loop
          command: ./docker-test.acceptance.sh #&& sudo find logs/acceptance -type f -delete
          no_output_timout: 20m
      - run: sudo chown -R circleci:circleci logs && ./.circleci/upload-node-metrics.sh && ./.circleci/archive-logs.sh
      - store_artifacts:
          path: logs

  notify_github_about_dashboard:
    machine: true
    steps:
      - checkout
      - run: python ./.circleci/post-dashboard-link.py

  success:
    machine: true
    steps:
      - run: echo 'Success'

  deploy_testnet:
    machine: true
    steps:
      - checkout
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker pull $DOCKER_IMAGE:$(./docker-tag.sh) && docker tag $DOCKER_IMAGE:$(./docker-tag.sh) orbs:export
#      - run: docker pull $DOCKER_IMAGE:master && docker tag $DOCKER_IMAGE:master orbs:export
      - run: git clone https://github.com/orbs-network/orbs-network-deploy-script && cd orbs-network-deploy-script && git checkout feature/support-v1
      - run: cd orbs-network-deploy-script && npm install -g typescript && npm install && DOCKER_TAG=export ./deploy-staging.sh

  e2e_testnet:
    machine: true
    steps:
      - checkout
      - run: ./git-submodules-checkout.sh
      - run: ./docker-build.sh
      - run: ./.circleci/e2e-testnet.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - acceptance
      - notify_github_about_dashboard
      - success:
          requires:
            - build
            - acceptance
      - deploy_testnet:
          requires:
            - success
          filters:
            branches:
              only:
                - feature/basic-testnet-configuration
      - e2e_testnet:
          requires:
            - deploy_testnet
          filters:
            branches:
              only:
                - feature/basic-testnet-configuration