version: 2
jobs:
  tests:
    docker:
      - image: circleci/golang:1.12.9
    resource_class: large
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run:
          command: ./test.sh
          no_output_timeout: 15m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: _reports
          destination: test-results
      - store_test_results:
          path: _reports

  races:
    docker:
      - image: circleci/golang:1.12.9
    resource_class: large
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run:
          command: ./test.races.sh
          no_output_timeout: 25m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  memory_leaks:
    docker:
      - image: circleci/golang:1.12.9
    resource_class: xlarge
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run: ./test.goroutine-leaks.sh
      - run: ./test.memory-leaks.sh

  flakiness:
    docker:
      - image: itamararjuan/golang_with_node_aws
    parallelism: 6
    resource_class: xlarge
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run:
          command: ./test.flakiness.sh
          no_output_timeout: 25m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  nightly:
    docker:
      - image: circleci/golang:1.12.9
    parallelism: 6
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: ./.circleci/nightly.sh
          no_output_timeout: 300m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: /go/src/github.com/orbs-network/orbs-network-go/_reports
          destination: test-results
      - store_test_results:
          path: _reports

  node_docker_build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./docker/build/build-docker-node.sh
      - run: ./.circleci/release-node-to-ecr.sh

  gamma_docker_build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./docker/build/build-docker-gamma.sh #TODO dedup commonalities between this and build-docker-node.sh
      - run: ./.circleci/release-gamma-to-ecr.sh

  node_e2e:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./.circleci/install-go.sh
      - run: ./.circleci/install-node.sh
      - run: ./.circleci/retry.sh 5 go get github.com/orbs-network/go-junit-report
      - run: ./.circleci/install-docker-compose.sh
      # Logs here belong to root
      - run: sudo rm -rf _logs
      - run:
          command: ./docker/test/test.sh
          name: "Docker test with Lean Helix Consensus"
          environment:
            CONSENSUSALGO: leanhelix
      - store_test_results:
          path: _reports
      - store_artifacts:
          path: _logs
      - store_artifacts:
          path: _out

  gamma_e2e: #TODO dedup common steps with node_e2e
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./.circleci/install-go.sh
      - run: ./.circleci/install-node.sh
      - run: ./.circleci/retry.sh 5 go get github.com/orbs-network/go-junit-report
      - run: ./.circleci/install-docker-compose.sh
      - run: ./docker/test/gamma-e2e.sh
      - store_test_results:
          path: _reports
      - store_artifacts:
          path: _out

  marvin_tests:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - run: ./.circleci/marvin-stress.sh #TODO rename file

  marvin_report_results:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - run: echo "report results to github if branch != master"
      - run: echo "report results to slack"

  deploy_testnet:
    docker:
      - image: itamararjuan/golang_with_node_aws
    steps:
      - checkout
      - run: ./.circleci/set-aws-credentials.sh
      - run: ./.circleci/deploy-testnet.sh

  ganache_related_tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./.circleci/install-go.sh
      - run: ./.circleci/retry.sh 5 go get github.com/orbs-network/go-junit-report
      - run: ./docker/test/ganache-related-test.sh
      - store_artifacts:
          path: _out
          destination: test-output
      - store_test_results:
          path: _reports

  e2e_testnet_benchmark:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run: sleep 300
      - run: ./.circleci/e2e-testnet.sh 42 40
      - store_test_results:
          path: _reports

  e2e_testnet_leanhelix:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get -u github.com/orbs-network/go-junit-report
      - run: sleep 300
      - run: ./.circleci/e2e-testnet.sh 2013 2011
      - store_test_results:
          path: _reports

  deploy_new_chain_pr_only:
    docker:
      - image: itamararjuan/golang_with_node_aws
    working_directory: /go/src/github.com/orbs-network/orbs-network-go/
    environment:
      BOOTSTRAP_URL: "https://boyar-testnet-bootstrap.s3-us-west-2.amazonaws.com/boyar/config.json"
      BOOTSTRAP_S3_URI: "s3://boyar-testnet-bootstrap/boyar/config.json"
      TESTNET_NODE_IP: "35.161.123.97"
      TESTNET_IGNORE_IPS: ""
    steps:
      - checkout
      - run: ./.circleci/retry.sh 5 go get github.com/orbs-network/go-junit-report #TODO remove as this shouldn't actually run the tests
      - run: ./.circleci/chain_on_pr.sh #TODO this step should only deploy, and return when then chain is closing blocks; tests will run in Marvin.
      - store_test_results:
          path: _reports
      - store_artifacts:
          path: _out

  release_ga:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/release.sh

  deploy_audit_node:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - run: echo "updating the boyar config for the Core Team audit node" #TODO reuse code that updates boyar config on testnet?

workflows:
  version: 2
  build: #TODO consider splitting into separate workflows: PR, merge to master, tagged release
    jobs:
      - tests:
          filters:
            tags:
              only: /^v.*/
      - races
      - memory_leaks
      - node_docker_build
      - gamma_docker_build
      - node_e2e:
          requires:
            - node_docker_build
          filters:
            tags:
              only: /^v.*/
      - gamma_e2e:
          requires:
            - gamma_docker_build
          filters:
            tags:
              only: /^v.*/
      - flakiness
      - ganache_related_tests
      - deploy_testnet:
          requires:
            - node_e2e
          filters:
            branches:
              only:
                - master
      - deploy_new_chain_pr_only: #TODO unify with deploy_testnet job if we want to keep this a single workflow; marvin needs to run against the deployed chain as well
          requires:
            - node_docker_build
            - tests # no point in deploying to testnet if one of the fast tests has failed
          filters:
            branches:
              ignore: master
      - e2e_testnet_leanhelix:
          requires:
            - deploy_testnet
      - marvin_tests:
          requires:
            - deploy_testnet
      - marvin_report_results:
          requires:
            - marvin_tests
      - release_ga:
          requires:
            - tests
            - node_e2e
            - gamma_e2e
            - marvin_report_results
            - ganache_related_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - deploy_audit_node:
          requires:
            - release_ga
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly
